# Generated by Django 5.2.3 on 2025-07-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_ticket_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_panel.ticket')),
            ],
            bases=('user_panel.ticket', models.Model),
        ),
    ]
