# Generated by Django 5.2.3 on 2025-07-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_archivedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Active Ticket',
                'verbose_name_plural': 'Active Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_panel.ticket',),
        ),
        migrations.DeleteModel(
            name='ArchivedTicket',
        ),
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Ticket',
                'verbose_name_plural': 'Archived Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_panel.ticket',),
        ),
    ]
